blank_issues_enabled: false
contact_links:
  - name: 💬 Support via Discord
    url: https://discord.gg/GMunyuG3wg
    about: Chat with other SeerrPlay users and contributors
  - name: 💬 Support via GitHub Discussions
    url: https://github.com/seerrplay-project/seerrplay-server/discussions
    about: Ask questions and discuss with other community members
